[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "alpaca-cli"
version = "0.1.0"
dependencies = ["huggingface_hub", "httpx"]
scripts = { alpaca = "alpaca:main" }
